// @ts-check
/**
 * codegen-enums —— 从后端 enums.json 生成前端 enum.ts（枚举 label 单源同步）。
 *
 * 契约（架构决策 G16 / 6.12）：枚举 label 是**后端单源**，可信源为 janus-server
 * 的 `src/locales/{lang}/enums.json`，与服务端导出（Excel/CSV 的 code→label）共享
 * 同一份译文。本脚本读取该 json，生成 `src/locales/{lang}/enum.ts`，零漂移。
 *
 * 产物**禁手改**：要改枚举 label 改后端 enums.json 后重跑 `pnpm codegen`。
 *
 * 用法：node scripts/codegen-enums.mjs
 *   可选环境变量 JANUS_SERVER_DIR 覆盖后端仓库根目录（默认同级 ../janus-server）。
 */

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const WEB_ROOT = resolve(__dirname, '..');
const SERVER_DIR = process.env.JANUS_SERVER_DIR
  ? resolve(process.env.JANUS_SERVER_DIR)
  : resolve(WEB_ROOT, '..', 'janus-server');

/** 与后端 supported_locales 对齐；codegen 双语产物。 */
const LOCALES = ['zh-CN', 'en-US'];

/** `enum.userStatus.active` → 取中段 `userStatus`（用于分组注释）。 */
function enumGroupOf(key) {
  const parts = key.split('.');
  return parts.length >= 3 ? parts[1] : '';
}

/** 小驼峰 → 大驼峰，仅用于分组注释（`userStatus` → `UserStatus`）。 */
function pascal(camel) {
  return camel ? camel[0].toUpperCase() + camel.slice(1) : camel;
}

function readBackendEnums(locale) {
  const path = join(SERVER_DIR, 'src', 'locales', locale, 'enums.json');
  let raw;
  try {
    raw = readFileSync(path, 'utf-8');
  } catch (err) {
    throw new Error(
      `读取后端枚举词条失败：${path}\n` +
        `请确认 janus-server 仓库在 ${SERVER_DIR}（或设 JANUS_SERVER_DIR）。\n` +
        `原始错误：${err instanceof Error ? err.message : String(err)}`,
    );
  }
  const data = JSON.parse(raw);
  if (data === null || typeof data !== 'object' || Array.isArray(data)) {
    throw new Error(`后端枚举词条须为扁平 JSON 对象：${path}`);
  }
  return /** @type {Record<string, string>} */ (data);
}

/** 把扁平词条渲染成带分组注释、稳定排序的 enum.ts 源码。 */
function renderEnumModule(locale, entries) {
  const isZh = locale === 'zh-CN';
  const header = isZh
    ? [
        '/**',
        ' * 枚举 label —— 【codegen 自动生成，请勿手改】。',
        ' *',
        ' * 由 `pnpm codegen` 从 janus-server 的 `src/locales/' + locale + '/enums.json`',
        ' * 生成（架构决策 G16 / 6.12：枚举 label 后端单源，与服务端导出共享译文）。',
        ' * 要改 label：改后端 enums.json 后重跑 `pnpm codegen`。',
        ' *',
        ' * 键名约定：`enum.{枚举名小驼峰}.{code}`。',
        ' */',
      ]
    : [
        '/**',
        ' * Enum labels — 【auto-generated by codegen, do NOT edit by hand】.',
        ' *',
        ' * Generated by `pnpm codegen` from janus-server `src/locales/' + locale + '/enums.json`',
        ' * (architecture decision G16 / 6.12: enum labels are backend single-source,',
        ' * sharing translations with server-side export). To change a label: edit the',
        ' * backend enums.json, then re-run `pnpm codegen`.',
        ' *',
        ' * Key convention: `enum.{enumNameCamel}.{code}`.',
        ' */',
      ];

  // 按「枚举名首次出现顺序」分组，组内保留 json 原序（json 已是源单序）。
  const keys = Object.keys(entries);
  /** @type {Map<string, string[]>} */
  const groups = new Map();
  for (const key of keys) {
    const group = enumGroupOf(key);
    if (!groups.has(group)) groups.set(group, []);
    groups.get(group)?.push(key);
  }

  const lines = [...header, 'const enums: Record<string, string> = {'];
  for (const [group, groupKeys] of groups) {
    if (group) lines.push(`  // ${pascal(group)}`);
    for (const key of groupKeys) {
      const value = entries[key].replace(/\\/g, '\\\\').replace(/'/g, "\\'");
      lines.push(`  '${key}': '${value}',`);
    }
  }
  lines.push('};', '', 'export default enums;', '');
  return lines.join('\n');
}

function main() {
  for (const locale of LOCALES) {
    const entries = readBackendEnums(locale);
    const source = renderEnumModule(locale, entries);
    const outPath = join(WEB_ROOT, 'src', 'locales', locale, 'enum.ts');
    mkdirSync(dirname(outPath), { recursive: true });
    writeFileSync(outPath, source, 'utf-8');
    const count = Object.keys(entries).length;
    console.log(`✓ ${locale}: ${count} 条枚举 label → src/locales/${locale}/enum.ts`);
  }
}

main();
