/**
 * Enum labels — 【auto-generated by codegen, do NOT edit by hand】.
 *
 * Generated by `pnpm codegen` from janus-server `src/locales/en-US/enums.json`
 * (architecture decision G16 / 6.12: enum labels are backend single-source,
 * sharing translations with server-side export). To change a label: edit the
 * backend enums.json, then re-run `pnpm codegen`.
 *
 * Key convention: `enum.{enumNameCamel}.{code}`.
 */
const enums: Record<string, string> = {
  // ActiveStatus
  'enum.activeStatus.active': 'Active',
  'enum.activeStatus.disabled': 'Disabled',
  // UsageStatus
  'enum.usageStatus.success': 'Success',
  'enum.usageStatus.error': 'Error',
  'enum.usageStatus.timeout': 'Timeout',
  // AuditOutcome
  'enum.auditOutcome.success': 'Success',
  'enum.auditOutcome.failure': 'Failure',
  // LoginFailureReason
  'enum.loginFailureReason.bad_credentials': 'Incorrect username or password',
  'enum.loginFailureReason.user_disabled': 'Account disabled',
  'enum.loginFailureReason.user_not_found': 'User not found',
  'enum.loginFailureReason.account_locked': 'Account locked',
  // UserStatus
  'enum.userStatus.active': 'Active',
  'enum.userStatus.disabled': 'Disabled',
  // OauthSource
  'enum.oauthSource.wecom': 'WeCom',
  // ApiKeyStatus
  'enum.apiKeyStatus.active': 'Active',
  'enum.apiKeyStatus.disabled': 'Disabled',
  // MenuType
  'enum.menuType.catalog': 'Catalog',
  'enum.menuType.menu': 'Menu',
  'enum.menuType.button': 'Button',
  // ChannelStatus
  'enum.channelStatus.active': 'Active',
  'enum.channelStatus.disabled': 'Disabled',
  // ChannelKeyStatus
  'enum.channelKeyStatus.active': 'Active',
  'enum.channelKeyStatus.disabled': 'Disabled',
  // GrantScope
  'enum.grantScope.user': 'User',
  'enum.grantScope.department': 'Department',
  // QuotaScope
  'enum.quotaScope.user': 'User',
  'enum.quotaScope.department': 'Department',
  'enum.quotaScope.global': 'Global',
  // QuotaPeriod
  'enum.quotaPeriod.daily': 'Daily',
  'enum.quotaPeriod.monthly': 'Monthly',
  'enum.quotaPeriod.total': 'Total',
  // QuotaMetric
  'enum.quotaMetric.tokens': 'Tokens',
  'enum.quotaMetric.requests': 'Requests',
  'enum.quotaMetric.cost': 'Cost',
  // RateLimitScope
  'enum.rateLimitScope.user': 'User',
  'enum.rateLimitScope.department': 'Department',
  'enum.rateLimitScope.global': 'Global',
  'enum.rateLimitScope.api_key': 'API Key',
  // ConfigValueType
  'enum.configValueType.string': 'String',
  'enum.configValueType.int': 'Integer',
  'enum.configValueType.bool': 'Boolean',
  'enum.configValueType.json': 'JSON',
  // AttachBizType
  'enum.attachBizType.avatar': 'Avatar',
  'enum.attachBizType.attachment': 'Attachment',
};

export default enums;
